# Generated by Django 4.1.6 on 2023-02-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('4', 'OTROS'), ('1', 'Contador'), ('3', 'ECONOMISTA'), ('2', 'ADMINISTRADOR')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
