# Generated by Django 4.1.6 on 2023-02-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_empleado_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('3', 'ECONOMISTA'), ('1', 'Contador'), ('2', 'ADMINISTRADOR'), ('4', 'OTROS')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
