# Generated by Django 4.1.6 on 2023-02-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_empleado_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('4', 'OTROS'), ('3', 'ECONOMISTA'), ('1', 'Contador'), ('2', 'ADMINISTRADOR')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
