# Generated by Django 4.1.6 on 2023-02-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_habilidades_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidad',
            field=models.ManyToManyField(to='personas.habilidades'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('1', 'Contador'), ('2', 'ADMINISTRADOR'), ('4', 'OTROS'), ('3', 'ECONOMISTA')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
