# Generated by Django 4.1.6 on 2023-02-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_empleado_habilidad_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('4', 'OTROS'), ('1', 'Contador'), ('2', 'ADMINISTRADOR'), ('3', 'ECONOMISTA')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
