# Generated by Django 4.1.6 on 2023-02-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_empleado_avatar_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('4', 'OTROS'), ('1', 'Contador'), ('3', 'ECONOMISTA'), ('2', 'ADMINISTRADOR')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
